name: Docker Image CI

on:
  create:
  push:
    tags-ignore: 
      - '**'
    branches:
      - master
      - fork/master

jobs:

  build_edge:
    name: "Build edge Docker image"
    if: github.event_name != 'create'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile-64 --tag buildenvironments/holy-build-box-64:edge
    - name: Push the Docker image
      run: docker push buildenvironments/holy-build-box-64:edge

  build_release:
    name: "Build release Docker image"
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile-64 --tag buildenvironments/holy-build-box-64:latest
        docker tag buildenvironments/holy-build-box-64:latest buildenvironments/holy-build-box-64:${{ github.event.ref }}
    - name: Push the Docker image
      run: |
        docker push buildenvironments/holy-build-box-64:latest
        docker push buildenvironments/holy-build-box-64:${{ github.event.ref }}
