name: Docker Image CI

on:
  push:
    branches:
      - master
      - fork/master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Docker Package Registry
      run: docker login docker.pkg.github.com -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile-64 --tag docker.pkg.github.com/build-environment/holy-build-box/hbb-64:edge
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/build-environment/holy-build-box/hbb-64:edge
